[240416] ci 파일 수정

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -28,4 +28,5 @@ jobs:
       - name: Install dependency
         id: install_dependency
         run: yarn install 2> >(tee log_${{ github.run_id }}.txt) ; \
-          test ${PIPESTATUS[0]} -eq 0 || { echo "yarn install failed." ; exit 1; }
+          if test ${PIPESTATUS[0]} -eq 0; then
+          echo "yarn install failed." ; exit 1;
